Repository uPortal-Project/NotificationPortlet, pull requests merged in 2018-09, with the labels that each got.

#100 Develop a new display strategy: notification-banner
  gradle.properties
  notification-portlet-webcomponents/notification-banner/.gitignore
  notification-portlet-webcomponents/notification-banner/README.md
  notification-portlet-webcomponents/notification-banner/babel.config.js
  notification-portlet-webcomponents/notification-banner/build.gradle
  notification-portlet-webcomponents/notification-banner/package-lock.json
  notification-portlet-webcomponents/notification-banner/package.json
  notification-portlet-webcomponents/notification-banner/public/favicon.ico
  notification-portlet-webcomponents/notification-banner/public/index.html
  notification-portlet-webcomponents/notification-banner/public/sample-notifications.json
  notification-portlet-webcomponents/notification-banner/src/App.vue
  notification-portlet-webcomponents/notification-banner/src/assets/logo.png
  notification-portlet-webcomponents/notification-banner/src/components/NotificationBanner.vue
  notification-portlet-webcomponents/notification-banner/src/main.js
  notification-portlet-webcomponents/notification-modal/src/components/NotificationModal.vue
  settings.gradle
Labels: work in progress

#103 enh(#102): Add notice filter by title / body regex matching.
  README.md
  notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/service/filter/BodyTextNotificationFilter.java
  notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/service/filter/FilteringNotificationServiceDecorator.java
  notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/service/filter/TextNotificationFilter.java
  notification-portlet-webapp/src/main/java/org/jasig/portlet/notice/service/filter/TitleTextNotificationFilter.java
  notification-portlet-webapp/src/main/webapp/WEB-INF/portlet.xml
Labels: enhancement

#111 fix: Fixes oidc transpilation for notification components
  notification-portlet-webcomponents/notification-banner/vue.config.js
  notification-portlet-webcomponents/notification-modal/vue.config.js
Labels: bug
